# Setup
title:            Courtney Crawford
description:          'LSU PhD Candidate in Astronomy'
url:              https://courtcraw.github.io
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Courtney Crawford'
  url:            https://twitter.com/

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
