# Setup
title:            Courtney Crawford
description:      'Astronomy Postdoc at the University of Sydney'
url:              https://courtcraw.github.io
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Courtney Crawford'
  url:            https://twitter.com/court_craw

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
